# Generated by Django 5.0.6 on 2025-03-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_referer_lead_user_agent_lead_utm_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('dancing_experience', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('experience_competing_teaching', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('practice_time_commitment', models.TextField(blank=True, null=True)),
                ('investment_willingness', models.TextField(blank=True, null=True)),
                ('long_term_commitment', models.BooleanField(default=False)),
                ('other_commitments', models.TextField(blank=True, null=True)),
                ('availability', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
