# Generated by Django 5.0.6 on 2026-01-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_castingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingregistration',
            name='omnisend_last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='castingregistration',
            name='omnisend_last_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='castingregistration',
            name='omnisend_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
