# Generated by Django 5.0.6 on 2026-01-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_omnisend_last_error_lead_omnisend_last_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='form_course_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='form_course_raw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='form_experience_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='form_experience_raw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='form_motivation_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='form_motivation_raw',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='form_schedule_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='form_schedule_raw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
