# Generated by Django 5.0.6 on 2026-03-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_form_course_key_lead_form_course_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_interest_raw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
