# Generated by Django 5.0.6 on 2026-05-24 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_lead_interest_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email_sequence_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailSequenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_position', models.IntegerField(choices=[(0, 'Inmediato'), (1, 'Día 1'), (2, 'Día 3'), (3, 'Día 7'), (4, 'Día 14'), (5, 'Día 21'), (6, 'Día 30'), (7, 'Día 45'), (8, 'Día 60')], verbose_name='Posición en secuencia')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('SKIPPED', 'Omitido')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID tarea Celery')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado el')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Log de secuencia de email',
                'verbose_name_plural': 'Logs de secuencia de emails',
                'ordering': ['lead', 'sequence_position'],
                'unique_together': {('lead', 'sequence_position')},
            },
        ),
    ]
