# Generated by Django 5.0.6 on 2026-06-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_email_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meta_event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
