# Generated by Django 5.0.6 on 2026-06-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_meta_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='capi_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='capi_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='capi_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
