# Generated by Django 5.0.6 on 2026-06-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_capi_response_lead_capi_sent_lead_capi_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='form_age_raw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
