# Generated by Django 5.0.6 on 2026-06-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_form_age_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='kommo_contact_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='kommo_last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='kommo_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
