# Generated by Django 5.0.6 on 2026-06-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_add_kommo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='kommo_deal_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
