# Generated by Django 5.0.6 on 2024-07-16 03:18

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Titulo')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Imagen')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Texto')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿Activo?')),
                ('tags', models.CharField(max_length=500, verbose_name='Etiquetas')),
                ('type', models.CharField(choices=[('Mision', 'Mision'), ('Vision', 'Vision')], max_length=50, verbose_name='Tipo')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Mision Vision',
                'verbose_name_plural': 'Mision Vision',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del Cliente')),
                ('profession', models.CharField(max_length=250, verbose_name='Profesión')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('video', models.FileField(blank=True, upload_to='videos/testimony', verbose_name='Video Testimonio')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('Top', 'Top')], max_length=50, verbose_name='Tipo')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Imagen Banner')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
            },
        ),
    ]
