# Generated by Django 5.0.6 on 2025-05-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_site', '0003_invitated'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='google_url',
            field=models.URLField(blank=True, help_text='Enlace a la reseña original en Google My Business', max_length=500, null=True, verbose_name='URL de Reseña en Google'),
        ),
    ]
