# Generated by Django 5.0.6 on 2024-09-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blog_images', verbose_name='Imagen'),
        ),
    ]
