# Generated by Django 5.0.6 on 2024-12-10 21:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300),
        ),
    ]
