# Generated by Django 5.0.6 on 2025-11-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content_alter_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('miraflores', 'Miraflores'), ('sanisidro', 'San Isidro'), ('surco', 'Santiago de Surco'), ('lince', 'Lince'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
