# Generated by Django 5.0.6 on 2024-07-07 04:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
    ]
