# Generated by Django 5.0.6 on 2024-07-17 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Caracteristicas')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='courses.course', verbose_name='Curso')),
            ],
        ),
    ]
