# Generated by Django 5.0.6 on 2024-07-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_district_alter_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.CharField(max_length=250, verbose_name='Horario'),
        ),
    ]
