# Generated by Django 5.0.6 on 2024-07-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_district_alter_course_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='month',
        ),
        migrations.AddField(
            model_name='course',
            name='image_banner_top',
            field=models.ImageField(blank=True, upload_to='images/course', verbose_name='Imagen Banner Top'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_banner_home',
            field=models.BooleanField(default=False, verbose_name='¿Aparecera en el Banner Home?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('Personalizada', 'Personalizada'), ('Grupal', 'Grupal'), ('Coreografia', 'Coreografia')], max_length=50, verbose_name='Tipo'),
        ),
    ]
