# Generated by Django 5.0.6 on 2024-10-04 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_month_course_image_banner_top_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
    ]
