# Generated by Django 5.0.6 on 2024-10-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(default=1, verbose_name='URL del Video'),
            preserve_default=False,
        ),
    ]
