# Generated by Django 5.0.6 on 2025-01-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_mp4',
            field=models.FileField(blank=True, null=True, upload_to='videos/course', verbose_name='Video MP4'),
        ),
    ]
