# Generated by Django 5.0.6 on 2025-01-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_video_mp4'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_video_url',
            field=models.ImageField(blank=True, upload_to='images/course', verbose_name='Imagen Video'),
        ),
    ]
