# Generated by Django 5.0.6 on 2025-05-11 16:55

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_image_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='benefits',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Beneficios Clave'),
        ),
        migrations.AddField(
            model_name='course',
            name='h1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Encabezado H1'),
        ),
        migrations.AddField(
            model_name='course',
            name='h2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Encabezado H2'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='course',
            name='technical_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Características Técnicas del Curso'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
            },
        ),
    ]
