# Generated by Django 5.0.6 on 2025-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_benefits_course_h1_course_h2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='body_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Titulo Cuerpo'),
        ),
    ]
