"""
Django settings for webluxe project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import logging
from pathlib import Path
import os
from dotenv import load_dotenv
import locale
locale.setlocale(locale.LC_ALL, 'es_ES.UTF-8')
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'  # Convertir a booleano

# load production server from .env
# ALLOWED_HOSTS = [
#     "localhost",
#     "localhost:85",
#     "127.0.0.1",
#     "92.112.184.29",
#     'srv618887.hstgr.nube'
# ]

ALLOWED_HOSTS = ['cubangrooveperu.com', 'www.cubangrooveperu.com', 'localhost','104.248.113.83', '127.0.0.1']

if os.getenv('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('REDIS_URL'),
            'TIMEOUT': 60 * 60,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': os.getenv('DJANGO_CACHE_DIR', r'C:\django_cache'),
            'TIMEOUT': 60 * 60,
            'OPTIONS': {'MAX_ENTRIES': 1000}
        }
    }



# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'ckeditor',
    'django_celery_beat',
    'django_celery_results',
]

LOCAL_APPS = [
    'users.apps.UsersConfig',
    'instructors.apps.InstructorsConfig',
    'courses.apps.CoursesConfig',
    'content_site.apps.ContentSiteConfig',
    'leads.apps.LeadsConfig',
    'blog.apps.BlogConfig',
]



INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

AUTH_USER_MODEL = 'users.CustomUser' # new

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',    # 1. Guarda en caché
    # 'webluxe.middleware.slash_flexible.SlashFlexibleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware', # 2. Sirve desde caché
]

ROOT_URLCONF = 'webluxe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # new
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'webluxe.config.context_processors.global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'webluxe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }

}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),] # new
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # new
STATICFILES_FINDERS = [
"django.contrib.staticfiles.finders.FileSystemFinder",
"django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'



EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")


RECAPTCHA_SITE_KEY = os.getenv("RECAPTCHA_SITE_KEY")
RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY")

CACHE_MIDDLEWARE_SECONDS = 60 * 60
CACHE_MIDDLEWARE_KEY_PREFIX = ""

# --- Celery ---
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Lima'
CELERY_ENABLE_UTC = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# En desarrollo sin Redis, ejecutar tareas de forma síncrona en el mismo proceso
if DEBUG and not os.getenv('CELERY_BROKER_URL'):
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = False  # No cortar la secuencia si una falla

_all_delays = {
    0: 0,        # inmediato
    1: 60,       # día 1  (PRUEBA: 1 min — producción: 86400)
    2: 120,      # día 3  (PRUEBA: 2 min — producción: 259200)
    3: 180,      # día 7  (PRUEBA: 3 min — producción: 604800)
    4: 240,      # día 14 (PRUEBA: 4 min — producción: 1209600)
    5: 300,      # día 21 (PRUEBA: 5 min — producción: 1814400)
    6: 360,      # día 30 (PRUEBA: 6 min — producción: 2592000)
    7: 420,      # día 45 (PRUEBA: 7 min — producción: 3888000)
    8: 480,      # día 60 (PRUEBA: 8 min — producción: 5184000)
}

_dev_limit = int(os.getenv('EMAIL_SEQUENCE_DEV_LIMIT', 9))
EMAIL_SEQUENCE_DELAYS = dict(list(_all_delays.items())[:_dev_limit])

APPEND_SLASH = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'detailed': {
            'format': '{asctime} | {levelname} | {message}',
            'style': '{',
        },
    },

    'handlers': {
        'bot_protection_handler': {
            'class': 'logging.FileHandler',
            'filename': '/var/log/cubangroove/bot_protection.log',
            'formatter': 'detailed',
            'encoding': 'utf-8',
            'mode': 'a',  # ← ESTO ERA LO QUE FALTABA
        },
    },

    'loggers': {
        'bot_protection': {
            'handlers': ['bot_protection_handler'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}